---
extends: default

ignore: |
  docs/pnpm-lock.yaml
  internal/configuration/test_resources/config_bad_quoting.yml
  web/pnpm-lock.yaml
  web/node_modules/
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/bug-report.yml
rules:
  document-end:
    level: warning
  empty-values:
    level: warning
  indentation:
    spaces: 2
    check-multi-line-strings: true
  line-length:
    max: 120
  octal-values: enable
...
